[project]
name = "recurpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prettytable>=3.15.1",
    "ruff>=0.9.9",
]
